bot:
  automerge: true
conda_forge_output_validation: true
travis:
  secure:
    BINSTAR_TOKEN: Ud7Fmta/AFCaPjx9M8gqsCfO9d+hMtn7gbd+LKkxQqikWVCoegAfo99w15AeVG2gUsRvDZxxY0/Pc9M3QJuYnALEn84scTlWe21y87mB6JVZSBWq6Ei43GZ0G5ruVaapBkRlhS36FVJyQJa0YtwhD3/AoSgwSupFH2jv+gQop8yNvAba5aY/z3DNSa68+xctYxHMmPFw5c1RsIwD/fv/n/dud+mkWCtV+yvdRMkJylojw6y5zzbsK9tEIAbViep13BWRHDfKClijaOtuxmT2et8KJEGOwHFnEJ14XiBPVLclVJh0bi0ROrwEvhzjs40sqvLsIbwlm0sGE+dJeOKNsX1kfuCSrGu3w20ToOlaeQqRrHQG1udfrDnhu08FNjXE8DuXWH6RgQ6N8wIT8lXYHG0/mChxaWK1ffA7ESY21uLm+/S/aYlPc50R/t0okBDbjdg1WFFBXuGvvMcjciFwbVAFSRF/xCOt9eLpF9nkLDTi0CC7sDyn6lpnBFFjbfFHhRKiNmY7kj+p0xzHTSsK04RqrQ9na+bNMebdiEIPZhFECdzammpSQVwOlPGDzXy90Ach85d8YCFG/YAyCnz0RiCn9AOsk3mo10t3LRuVCIMko2Qyx4zQTKlLmXZdXLRK8f03VTx1MMx6cq/RBaN6l6CGGeaQJP+fZK3vmbPuCbw=
